version: '3.4'

services:
  auth:
    image: ${DOCKER_REGISTRY-}auth
    build:
      context: .
      dockerfile: Auth/Dockerfile
  messages:
    image: ${DOCKER_REGISTRY-}messages
    build:
      context: .
      dockerfile: Messages/Dockerfile
  users:
    image: ${DOCKER_REGISTRY-}user
    build:
      context: .
      dockerfile: User/Dockerfile
  dialog:
    image: ${DOCKER_REGISTRY-}dialog
    build:
      context: .
      dockerfile: Dialog/Dockerfile